Repository Leets-Official/GachTaxi-BE, pull requests merged in 2025-01, with the labels that each got.

#5 Feat #5 채팅을 위한 웹소켓 + 레디스 기본 설정
  src/main/java/com/gachtaxi/domain/chat/dto/request/ChatMessage.java
  src/main/java/com/gachtaxi/domain/chat/dto/request/ChatMessageRequest.java
  src/main/java/com/gachtaxi/domain/chat/exception/CustomMessagingException.java
  src/main/java/com/gachtaxi/domain/chat/exception/CustomSerializationException.java
  src/main/java/com/gachtaxi/domain/chat/exception/ErrorMessage.java
  src/main/java/com/gachtaxi/domain/chat/exception/RedisSubscribeException.java
  src/main/java/com/gachtaxi/domain/chat/redis/RedisChatPublisher.java
  src/main/java/com/gachtaxi/domain/chat/redis/RedisChatSubscriber.java
  src/main/java/com/gachtaxi/global/config/RedisConfig.java
  src/main/java/com/gachtaxi/global/config/WebSocketConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: ⚙ Setting, ✨ Feature

#10 Chore #10 개발서버 cicd 구축
  .github/workflows/dev.yml
  Dockerfile-dev
  gradlew
Labels: ⚙ Setting

#11 Feat #11 카카오 로그인 구현
  src/main/java/com/gachtaxi/domain/members/controller/AuthController.java
  src/main/java/com/gachtaxi/domain/members/controller/MemberController.java
  src/main/java/com/gachtaxi/domain/members/controller/ResponseMessage.java
  src/main/java/com/gachtaxi/domain/members/dto/request/UserSignUpRequestDto.java
  src/main/java/com/gachtaxi/domain/members/entity/Members.java
  src/main/java/com/gachtaxi/domain/members/entity/enums/Gender.java
  src/main/java/com/gachtaxi/domain/members/entity/enums/Role.java
  src/main/java/com/gachtaxi/domain/members/exception/DuplicatedStudentNumberException.java
  src/main/java/com/gachtaxi/domain/members/exception/ErrorMessage.java
  src/main/java/com/gachtaxi/domain/members/repository/MemberRepository.java
  src/main/java/com/gachtaxi/domain/members/service/AuthService.java
  src/main/java/com/gachtaxi/domain/members/service/MemberService.java
  src/main/java/com/gachtaxi/global/auth/enums/OauthLoginStatus.java
  src/main/java/com/gachtaxi/global/auth/jwt/dto/JwtTokenDto.java
  src/main/java/com/gachtaxi/global/auth/jwt/exception/JwtErrorMessage.java
  src/main/java/com/gachtaxi/global/auth/jwt/exception/TokenInvalidException.java
  src/main/java/com/gachtaxi/global/auth/jwt/service/JwtService.java
  src/main/java/com/gachtaxi/global/auth/jwt/util/CookieUtil.java
  src/main/java/com/gachtaxi/global/auth/jwt/util/JwtExtractor.java
  src/main/java/com/gachtaxi/global/auth/jwt/util/JwtProvider.java
  src/main/java/com/gachtaxi/global/auth/jwt/util/JwtRedisUtil.java
  src/main/java/com/gachtaxi/global/auth/kakao/dto/KaKaoDTO.java
  src/main/java/com/gachtaxi/global/auth/kakao/util/KakaoUtil.java
  src/main/java/com/gachtaxi/global/auth/mapper/OauthMapper.java
  src/main/java/com/gachtaxi/global/common/entity/BaseEntity.java
  src/main/java/com/gachtaxi/global/common/exception/BaseException.java
  src/main/resources/application-local.yml
Labels: ✨ Feature

#12 Feat #12 채팅 엔티티 설정 및 인터셉터 구현
  src/main/java/com/gachtaxi/GachtaxiApplication.java
  src/main/java/com/gachtaxi/domain/chat/dto/request/ChatMessage.java
  src/main/java/com/gachtaxi/domain/chat/dto/request/ChatMessageRequest.java
  src/main/java/com/gachtaxi/domain/chat/entity/ChattingMessage.java
  src/main/java/com/gachtaxi/domain/chat/entity/ChattingParticipant.java
  src/main/java/com/gachtaxi/domain/chat/entity/ChattingRoom.java
  src/main/java/com/gachtaxi/domain/chat/exception/ChatSubscribeException.java
  src/main/java/com/gachtaxi/domain/chat/exception/ErrorMessage.java
  src/main/java/com/gachtaxi/domain/chat/interceptor/CustomChannelInterceptor.java
  src/main/java/com/gachtaxi/domain/chat/interceptor/strategy/ChatStrategyHandler.java
  src/main/java/com/gachtaxi/domain/chat/interceptor/strategy/DefaultCommandStrategy.java
  src/main/java/com/gachtaxi/domain/chat/interceptor/strategy/StompCommandStrategy.java
  src/main/java/com/gachtaxi/domain/chat/interceptor/strategy/StompConnectStrategy.java
  src/main/java/com/gachtaxi/domain/chat/interceptor/strategy/StompSubscribeStrategy.java
  src/main/java/com/gachtaxi/domain/chat/repository/ChattingMessageRepository.java
  src/main/java/com/gachtaxi/domain/chat/repository/ChattingParticipantRepository.java
  src/main/java/com/gachtaxi/domain/chat/repository/ChattingRoomRepository.java
  src/main/java/com/gachtaxi/global/auth/jwt/exception/JwtErrorMessage.java
  src/main/java/com/gachtaxi/global/auth/jwt/exception/TokenNotExistException.java
  src/main/java/com/gachtaxi/global/auth/jwt/util/JwtProvider.java
  src/main/java/com/gachtaxi/global/config/WebSocketConfig.java
  src/main/resources/application-local.yml
Labels: ✨ Feature

#14 Feat #14 인증 인가 로직 구현
  build.gradle
  src/main/java/com/gachtaxi/domain/members/controller/AuthController.java
  src/main/java/com/gachtaxi/domain/members/controller/ResponseMessage.java
  src/main/java/com/gachtaxi/domain/members/dto/request/UserSignUpRequestDto.java
  src/main/java/com/gachtaxi/domain/members/repository/MemberRepository.java
  src/main/java/com/gachtaxi/global/auth/jwt/annotation/CurrentMemberId.java
  src/main/java/com/gachtaxi/global/auth/jwt/authentication/CustomAccessDeniedHandler.java
  src/main/java/com/gachtaxi/global/auth/jwt/authentication/CustomAuthenticationEntryPoint.java
  src/main/java/com/gachtaxi/global/auth/jwt/exception/CookieNotFoundException.java
  src/main/java/com/gachtaxi/global/auth/jwt/exception/JwtErrorMessage.java
  src/main/java/com/gachtaxi/global/auth/jwt/exception/RefreshTokenNotFoundException.java
  src/main/java/com/gachtaxi/global/auth/jwt/exception/TokenExpiredException.java
  src/main/java/com/gachtaxi/global/auth/jwt/exception/TokenInvalidException.java
  src/main/java/com/gachtaxi/global/auth/jwt/exception/UserEmailNotFoundException.java
  src/main/java/com/gachtaxi/global/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/gachtaxi/global/auth/jwt/service/JwtService.java
  src/main/java/com/gachtaxi/global/auth/jwt/user/JwtUserDetails.java
  src/main/java/com/gachtaxi/global/auth/jwt/user/JwtUserDetailsService.java
  src/main/java/com/gachtaxi/global/auth/jwt/util/CookieUtil.java
  src/main/java/com/gachtaxi/global/auth/jwt/util/JwtExtractor.java
  src/main/java/com/gachtaxi/global/auth/jwt/util/JwtProvider.java
  src/main/java/com/gachtaxi/global/auth/jwt/util/JwtRedisUtil.java
  src/main/java/com/gachtaxi/global/config/PermitUrlConfig.java
  src/main/java/com/gachtaxi/global/config/SecurityConfig.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: ✨ Feature

#21 Feat #20 카카오 로그인 로직 변경
  src/main/java/com/gachtaxi/domain/members/controller/AuthController.java
  src/main/java/com/gachtaxi/domain/members/dto/request/TmpMemberDto.java
  src/main/java/com/gachtaxi/domain/members/entity/Members.java
  src/main/java/com/gachtaxi/domain/members/entity/enums/UserStatus.java
  src/main/java/com/gachtaxi/domain/members/service/AuthService.java
  src/main/java/com/gachtaxi/domain/members/service/MemberService.java
  src/main/java/com/gachtaxi/global/auth/jwt/service/JwtService.java
  src/main/java/com/gachtaxi/global/auth/jwt/util/JwtProvider.java
  src/main/java/com/gachtaxi/global/auth/kakao/dto/KaKaoDTO.java
  src/main/java/com/gachtaxi/global/auth/mapper/OauthMapper.java
  src/main/java/com/gachtaxi/global/config/SecurityConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: ✨ Feature

#23 Feat #21 Presigned Url 반환 API 구현 및 스웨거 설정 추가
  src/main/java/com/gachtaxi/global/common/image/ImageUtil.java
  src/main/java/com/gachtaxi/global/common/image/controller/ImageController.java
  src/main/java/com/gachtaxi/global/common/image/controller/ResponseMessage.java
  src/main/java/com/gachtaxi/global/config/AwsS3Config.java
  src/main/java/com/gachtaxi/global/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: ⚙ Setting, ✨ Feature

#24 Feat #26 학교 이메일 인증 구현
  build.gradle
  src/main/java/com/gachtaxi/domain/members/controller/AdminMemberController.java
  src/main/java/com/gachtaxi/domain/members/controller/AuthController.java
  src/main/java/com/gachtaxi/domain/members/controller/MemberController.java
  src/main/java/com/gachtaxi/domain/members/dto/request/InactiveMemberAuthCodeRequestDto.java
  src/main/java/com/gachtaxi/domain/members/dto/request/InactiveMemberDto.java
  src/main/java/com/gachtaxi/domain/members/dto/response/InactiveMemberResponseDto.java
  src/main/java/com/gachtaxi/domain/members/entity/Members.java
  src/main/java/com/gachtaxi/domain/members/exception/EmailFormInvalidException.java
  src/main/java/com/gachtaxi/domain/members/exception/ErrorMessage.java
  src/main/java/com/gachtaxi/domain/members/exception/MemberNotFoundException.java
  src/main/java/com/gachtaxi/domain/members/service/AuthService.java
  src/main/java/com/gachtaxi/domain/members/service/MemberService.java
  src/main/java/com/gachtaxi/global/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/gachtaxi/global/auth/jwt/service/JwtService.java
  src/main/java/com/gachtaxi/global/auth/jwt/util/JwtExtractor.java
  src/main/java/com/gachtaxi/global/auth/jwt/util/JwtRedisUtil.java
  src/main/java/com/gachtaxi/global/common/mail/dto/request/EmailAddressDto.java
  src/main/java/com/gachtaxi/global/common/mail/dto/request/NewTemplateRequestDto.java
  src/main/java/com/gachtaxi/global/common/mail/exception/AuthCodeExpirationException.java
  src/main/java/com/gachtaxi/global/common/mail/exception/AuthCodeNotMatchException.java
  src/main/java/com/gachtaxi/global/common/mail/message/ErrorMessage.java
  src/main/java/com/gachtaxi/global/common/mail/message/ResponseMessage.java
  src/main/java/com/gachtaxi/global/common/mail/service/EmailService.java
  src/main/java/com/gachtaxi/global/common/mail/service/SesClientTemplateService.java
  src/main/java/com/gachtaxi/global/common/redis/RedisUtil.java
  src/main/java/com/gachtaxi/global/config/PermitUrlConfig.java
  src/main/java/com/gachtaxi/global/config/SesClinetConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: 🐞 Bug, ✨ Feature

#25 Feat #25 채팅 비즈니스 로직 및 예외처리 구현
  src/main/java/com/gachtaxi/domain/chat/controller/ChattingController.java
  src/main/java/com/gachtaxi/domain/chat/controller/ResponseMessage.java
  src/main/java/com/gachtaxi/domain/chat/dto/request/ChatMessage.java
  src/main/java/com/gachtaxi/domain/chat/dto/request/ChatMessageRequest.java
  src/main/java/com/gachtaxi/domain/chat/dto/request/ChattingRoomResponse.java
  src/main/java/com/gachtaxi/domain/chat/entity/ChattingMessage.java
  src/main/java/com/gachtaxi/domain/chat/entity/ChattingParticipant.java
  src/main/java/com/gachtaxi/domain/chat/entity/ChattingRoom.java
  src/main/java/com/gachtaxi/domain/chat/entity/enums/MessageType.java
  src/main/java/com/gachtaxi/domain/chat/entity/enums/Status.java
  src/main/java/com/gachtaxi/domain/chat/exception/ChatSendEndPointException.java
  src/main/java/com/gachtaxi/domain/chat/exception/ChattingRoomNotFoundException.java
  src/main/java/com/gachtaxi/domain/chat/exception/ErrorMessage.java
  src/main/java/com/gachtaxi/domain/chat/exception/WebSocketSessionException.java
  src/main/java/com/gachtaxi/domain/chat/service/ChattingRoomService.java
  src/main/java/com/gachtaxi/domain/chat/service/ChattingService.java
  src/main/java/com/gachtaxi/domain/chat/stomp/CustomChannelInterceptor.java
  src/main/java/com/gachtaxi/domain/chat/stomp/strategy/ChatStrategyHandler.java
  src/main/java/com/gachtaxi/domain/chat/stomp/strategy/DefaultCommandStrategy.java
  src/main/java/com/gachtaxi/domain/chat/stomp/strategy/StompCommandStrategy.java
  src/main/java/com/gachtaxi/domain/chat/stomp/strategy/StompConnectStrategy.java
  src/main/java/com/gachtaxi/domain/chat/stomp/strategy/StompSendStrategy.java
  src/main/java/com/gachtaxi/domain/chat/stomp/strategy/StompSubscribeStrategy.java
  src/main/java/com/gachtaxi/global/common/exception/handler/StompExceptionHandler.java
  src/main/java/com/gachtaxi/global/config/PermitUrlConfig.java
  src/main/java/com/gachtaxi/global/config/WebSocketConfig.java
Labels: 🔨 Refactor, ✨ Feature

#15 Feat/#15/이벤트 기반 아키텍쳐 매칭 로직 구현
  .gitignore
  build.gradle
  src/main/java/com/gachtaxi/domain/matching/algorithm/dto/FindRoomResult.java
  src/main/java/com/gachtaxi/domain/matching/algorithm/service/MatchingAlgorithmService.java
  src/main/java/com/gachtaxi/domain/matching/algorithm/service/MockMatchingAlgorithmService.java
  src/main/java/com/gachtaxi/domain/matching/common/controller/AutoMatchingController.java
  src/main/java/com/gachtaxi/domain/matching/common/controller/ResponseMessage.java
  src/main/java/com/gachtaxi/domain/matching/common/dto/enums/AutoMatchingStatus.java
  src/main/java/com/gachtaxi/domain/matching/common/dto/request/AutoMatchingPostRequest.java
  src/main/java/com/gachtaxi/domain/matching/common/dto/response/AutoMatchingPostResponse.java
  src/main/java/com/gachtaxi/domain/matching/common/entity/MatchingRoom.java
  src/main/java/com/gachtaxi/domain/matching/common/entity/MatchingRoomTagInfo.java
  src/main/java/com/gachtaxi/domain/matching/common/entity/MemberMatchingRoomChargingInfo.java
  src/main/java/com/gachtaxi/domain/matching/common/entity/Route.java
  src/main/java/com/gachtaxi/domain/matching/common/entity/enums/MatchingRoomStatus.java
  src/main/java/com/gachtaxi/domain/matching/common/entity/enums/PaymentStatus.java
  src/main/java/com/gachtaxi/domain/matching/common/entity/enums/Tags.java
  src/main/java/com/gachtaxi/domain/matching/common/exception/ErrorMessage.java
  src/main/java/com/gachtaxi/domain/matching/common/exception/NoSuchMatchingRoomException.java
  src/main/java/com/gachtaxi/domain/matching/common/exception/NotActiveMatchingRoomException.java
  src/main/java/com/gachtaxi/domain/matching/common/repository/MatchingRoomRepository.java
  src/main/java/com/gachtaxi/domain/matching/common/repository/MatchingRoomTagInfoRepository.java
  src/main/java/com/gachtaxi/domain/matching/common/repository/MemberMatchingRoomChargingInfoRepository.java
  src/main/java/com/gachtaxi/domain/matching/common/repository/RouteRepository.java
  src/main/java/com/gachtaxi/domain/matching/common/service/AutoMatchingService.java
  src/main/java/com/gachtaxi/domain/matching/common/service/MatchingRoomService.java
  src/main/java/com/gachtaxi/domain/matching/event/dto/kafka_topic/MatchMemberJoinedEvent.java
  src/main/java/com/gachtaxi/domain/matching/event/dto/kafka_topic/MatchRoomCreatedEvent.java
  src/main/java/com/gachtaxi/domain/matching/event/service/kafka/AutoMatchingConsumer.java
  src/main/java/com/gachtaxi/domain/matching/event/service/kafka/AutoMatchingProducer.java
  src/main/java/com/gachtaxi/domain/matching/event/service/sse/SseService.java
  src/main/java/com/gachtaxi/domain/members/service/MemberService.java
  src/main/java/com/gachtaxi/global/config/kafka/KafkaConsumerConfig.java
  src/main/java/com/gachtaxi/global/config/kafka/KafkaProducerConfig.java
  src/main/java/com/gachtaxi/global/config/kafka/KafkaTopicsConfig.java
  src/main/resources/application-local.yml
Labels: ✨ Feature

#27 Feat #27 최초 회원가입 구현
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/com/gachtaxi/GachtaxiApplication.java
  src/main/java/com/gachtaxi/domain/members/controller/AuthController.java
  src/main/java/com/gachtaxi/domain/members/controller/MemberController.java
  src/main/java/com/gachtaxi/domain/members/dto/request/MemberAgreementRequestDto.java
  src/main/java/com/gachtaxi/domain/members/dto/request/MemberSupplmentRequestDto.java
  src/main/java/com/gachtaxi/domain/members/dto/response/OauthResponse.java
  src/main/java/com/gachtaxi/domain/members/entity/Members.java
  src/main/java/com/gachtaxi/domain/members/exception/DuplicatedEmailException.java
  src/main/java/com/gachtaxi/domain/members/exception/ErrorMessage.java
  src/main/java/com/gachtaxi/domain/members/service/AuthService.java
  src/main/java/com/gachtaxi/domain/members/service/MemberService.java
  src/main/java/com/gachtaxi/global/auth/jwt/dto/JwtTokenDto.java
  src/main/java/com/gachtaxi/global/auth/jwt/exception/JwtErrorMessage.java
  src/main/java/com/gachtaxi/global/auth/jwt/service/JwtService.java
  src/main/java/com/gachtaxi/global/auth/jwt/util/JwtExtractor.java
  src/main/java/com/gachtaxi/global/auth/jwt/util/JwtProvider.java
  src/main/java/com/gachtaxi/global/auth/kakao/dto/KaKaoDTO.java
  src/main/java/com/gachtaxi/global/auth/mapper/OauthMapper.java
  src/main/java/com/gachtaxi/global/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/gachtaxi/global/common/mail/message/ResponseMessage.java
  src/main/java/com/gachtaxi/global/common/mail/service/EmailService.java
  src/main/java/com/gachtaxi/global/config/PermitUrlConfig.java
Labels: ✨ Feature

#31 Feat #31 채팅 고도화
  build.gradle
  src/main/java/com/gachtaxi/domain/chat/controller/ChattingController.java
  src/main/java/com/gachtaxi/domain/chat/controller/ResponseMessage.java
  src/main/java/com/gachtaxi/domain/chat/dto/request/ChatMessage.java
  src/main/java/com/gachtaxi/domain/chat/dto/request/ChatMessageRequest.java
  src/main/java/com/gachtaxi/domain/chat/dto/response/ChatPageableResponse.java
  src/main/java/com/gachtaxi/domain/chat/dto/response/ChatResponse.java
  src/main/java/com/gachtaxi/domain/chat/dto/response/ChattingMessageResponse.java
  src/main/java/com/gachtaxi/domain/chat/dto/response/ChattingRoomResponse.java
  src/main/java/com/gachtaxi/domain/chat/entity/ChattingMessage.java
  src/main/java/com/gachtaxi/domain/chat/entity/ChattingParticipant.java
  src/main/java/com/gachtaxi/domain/chat/entity/ChattingRoom.java
  src/main/java/com/gachtaxi/domain/chat/entity/enums/ChatStatus.java
  src/main/java/com/gachtaxi/domain/chat/entity/enums/MessageType.java
  src/main/java/com/gachtaxi/domain/chat/event/WebSocketEventHandler.java
  src/main/java/com/gachtaxi/domain/chat/exception/ChattingParticipantNotFoundException.java
  src/main/java/com/gachtaxi/domain/chat/exception/ChattingRoomNotFoundException.java
  src/main/java/com/gachtaxi/domain/chat/exception/DuplicateSubscribeException.java
  src/main/java/com/gachtaxi/domain/chat/exception/ErrorMessage.java
  src/main/java/com/gachtaxi/domain/chat/exception/LastMessageTimeStampNullException.java
  src/main/java/com/gachtaxi/domain/chat/exception/UnSubscriptionException.java
  src/main/java/com/gachtaxi/domain/chat/repository/ChattingMessageRepository.java
  src/main/java/com/gachtaxi/domain/chat/repository/ChattingParticipantRepository.java
  src/main/java/com/gachtaxi/domain/chat/service/ChattingParticipantService.java
  src/main/java/com/gachtaxi/domain/chat/service/ChattingRoomService.java
  src/main/java/com/gachtaxi/domain/chat/service/ChattingService.java
  src/main/java/com/gachtaxi/domain/chat/stomp/strategy/StompConnectStrategy.java
  src/main/java/com/gachtaxi/domain/chat/stomp/strategy/StompSubscribeStrategy.java
  src/main/java/com/gachtaxi/global/common/exception/handler/CustomMessageExceptionHandler.java
  src/main/java/com/gachtaxi/global/config/WebSocketConfig.java
Labels: 🔨 Refactor, ✨ Feature

#38 Feat #38 매칭 필터링 및 알고리즘 구현
  src/main/java/com/gachtaxi/domain/matching/algorithm/service/MatchingAlgorithmService.java
  src/main/java/com/gachtaxi/domain/matching/algorithm/service/MockMatchingAlgorithmService.java
  src/main/java/com/gachtaxi/domain/matching/common/entity/MatchingRoom.java
  src/main/java/com/gachtaxi/domain/matching/common/entity/MatchingRoomTagInfo.java
  src/main/java/com/gachtaxi/domain/matching/common/entity/Route.java
  src/main/java/com/gachtaxi/domain/matching/common/exception/DuplicatedMatchingRoomException.java
  src/main/java/com/gachtaxi/domain/matching/common/exception/ErrorMessage.java
  src/main/java/com/gachtaxi/domain/matching/common/exception/PageNotFoundException.java
  src/main/java/com/gachtaxi/domain/matching/common/repository/MatchingRoomRepository.java
  src/main/java/com/gachtaxi/domain/matching/common/service/AutoMatchingService.java
  src/main/java/com/gachtaxi/domain/matching/common/service/MatchingRoomService.java
Labels: 🔨 Refactor, ✨ Feature

#37 Feat #37 구글 로그인 구현
  src/main/java/com/gachtaxi/domain/members/controller/AuthController.java
  src/main/java/com/gachtaxi/domain/members/controller/ResponseMessage.java
  src/main/java/com/gachtaxi/domain/members/dto/request/MemberIntegrationRequestDto.java
  src/main/java/com/gachtaxi/domain/members/dto/request/MemberTokenDto.java
  src/main/java/com/gachtaxi/domain/members/entity/Members.java
  src/main/java/com/gachtaxi/domain/members/exception/DuplicatedNickNameException.java
  src/main/java/com/gachtaxi/domain/members/exception/ErrorMessage.java
  src/main/java/com/gachtaxi/domain/members/repository/MemberRepository.java
  src/main/java/com/gachtaxi/domain/members/service/AuthService.java
  src/main/java/com/gachtaxi/domain/members/service/MemberService.java
  src/main/java/com/gachtaxi/global/auth/google/dto/GoogleAuthCode.java
  src/main/java/com/gachtaxi/global/auth/google/dto/GoogleTokenResponse.java
  src/main/java/com/gachtaxi/global/auth/google/dto/GoogleUserInfoResponse.java
  src/main/java/com/gachtaxi/global/auth/google/utils/GoogleUtils.java
  src/main/java/com/gachtaxi/global/auth/jwt/service/JwtService.java
  src/main/java/com/gachtaxi/global/common/mail/message/ResponseMessage.java
  src/main/java/com/gachtaxi/global/common/mail/service/EmailService.java
  src/main/java/com/gachtaxi/global/config/PermitUrlConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: 🔨 Refactor, ✨ Feature

#39 Feat #39 알림 도메인 및 FCM 구현
  .gitignore
  build.gradle
  src/main/java/com/gachtaxi/domain/members/controller/MemberController.java
  src/main/java/com/gachtaxi/domain/members/controller/ResponseMessage.java
  src/main/java/com/gachtaxi/domain/members/dto/request/FcmTokenRequest.java
  src/main/java/com/gachtaxi/domain/members/entity/Members.java
  src/main/java/com/gachtaxi/domain/members/service/MemberService.java
  src/main/java/com/gachtaxi/domain/notification/controller/NotificationController.java
  src/main/java/com/gachtaxi/domain/notification/controller/ResponseMessage.java
  src/main/java/com/gachtaxi/domain/notification/dto/response/NotificationInfoResponse.java
  src/main/java/com/gachtaxi/domain/notification/dto/response/NotificationResponse.java
  src/main/java/com/gachtaxi/domain/notification/entity/Notification.java
  src/main/java/com/gachtaxi/domain/notification/entity/enums/NotificationStatus.java
  src/main/java/com/gachtaxi/domain/notification/entity/enums/NotificationType.java
  src/main/java/com/gachtaxi/domain/notification/exception/ErrorMessage.java
  src/main/java/com/gachtaxi/domain/notification/exception/FcmTokenNotFoundException.java
  src/main/java/com/gachtaxi/domain/notification/exception/InvalidFcmTokenException.java
  src/main/java/com/gachtaxi/domain/notification/exception/MemberNotMatchException.java
  src/main/java/com/gachtaxi/domain/notification/exception/NotificationNotFoundException.java
  src/main/java/com/gachtaxi/domain/notification/repository/NotificationRepository.java
  src/main/java/com/gachtaxi/domain/notification/service/FcmService.java
  src/main/java/com/gachtaxi/domain/notification/service/NotificationService.java
  src/main/java/com/gachtaxi/global/config/FirebaseConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: ✨ Feature

#50 Fix #50 유저 정보 응답 수정
  src/main/java/com/gachtaxi/domain/members/controller/AuthController.java
  src/main/java/com/gachtaxi/domain/members/dto/request/MemberTokenDto.java
  src/main/java/com/gachtaxi/domain/members/dto/response/LoginDto.java
  src/main/java/com/gachtaxi/domain/members/dto/response/MemberLoginResponseDto.java
  src/main/java/com/gachtaxi/domain/members/dto/response/MemberResponseDto.java
  src/main/java/com/gachtaxi/domain/members/service/AuthService.java
  src/main/java/com/gachtaxi/domain/members/service/MemberService.java
Labels: 💻 Fix, ✨ Feature

#45 Feat/#44/자동 매칭 로직 버그 수정 및 sse 구독 로직 수정
  src/main/java/com/gachtaxi/domain/matching/algorithm/service/MatchingAlgorithmServiceImpl.java
  src/main/java/com/gachtaxi/domain/matching/common/controller/AutoMatchingController.java
  src/main/java/com/gachtaxi/domain/matching/common/dto/request/AutoMatchingPostRequest.java
  src/main/java/com/gachtaxi/domain/matching/common/exception/AlreadyInMatchingRoomException.java
  src/main/java/com/gachtaxi/domain/matching/common/exception/ErrorMessage.java
  src/main/java/com/gachtaxi/domain/matching/common/repository/MatchingRoomRepository.java
  src/main/java/com/gachtaxi/domain/matching/common/service/MatchingRoomService.java
  src/main/java/com/gachtaxi/domain/matching/event/dto/kafka_topic/MatchRoomCreatedEvent.java
  src/main/java/com/gachtaxi/domain/matching/event/service/kafka/AutoMatchingConsumer.java
  src/main/java/com/gachtaxi/domain/matching/event/service/sse/SseService.java
Labels: 💻 Fix, ✨ Feature

#55 FIX # 55 presigned url 확장자 추가
  src/main/java/com/gachtaxi/global/common/image/ImageUtil.java
  src/main/java/com/gachtaxi/global/common/image/controller/ImageController.java
Labels: 💻 Fix

#58 Feat/#57/ocicicd파이프라인구축
  .github/workflows/dev.yml
Labels: ⚙ Setting

#62 Refactor #62 알림 dto 간소화 및 mongodb로 이전
  src/main/java/com/gachtaxi/domain/notification/controller/NotificationController.java
  src/main/java/com/gachtaxi/domain/notification/dto/response/NotificationListResponse.java
  src/main/java/com/gachtaxi/domain/notification/dto/response/NotificationPageableResponse.java
  src/main/java/com/gachtaxi/domain/notification/dto/response/NotificationResponse.java
  src/main/java/com/gachtaxi/domain/notification/entity/Notification.java
  src/main/java/com/gachtaxi/domain/notification/entity/enums/NotificationType.java
  src/main/java/com/gachtaxi/domain/notification/entity/payload/FriendRequestPayload.java
  src/main/java/com/gachtaxi/domain/notification/entity/payload/MatchingPayload.java
  src/main/java/com/gachtaxi/domain/notification/entity/payload/NotificationPayload.java
  src/main/java/com/gachtaxi/domain/notification/repository/NotificationRepository.java
  src/main/java/com/gachtaxi/domain/notification/service/NotificationService.java
  src/main/java/com/gachtaxi/global/config/FirebaseConfig.java
Labels: 🔨 Refactor, 💻 Fix
