Repository Leets-Official/GachTaxi-BE, pull requests merged in 2025-03, with the labels that each got.

#130 Feat #130 채팅방 퇴장시 읽지 않음 수 업데이트
  src/main/java/com/gachtaxi/domain/chat/service/ChattingParticipantService.java
  src/main/java/com/gachtaxi/domain/chat/service/ChattingRoomService.java
  src/main/java/com/gachtaxi/domain/chat/service/ChattingService.java
Labels: ✨ Feature

#137 Refactor #137 닉네임 글자 수 제한 추가
  src/main/java/com/gachtaxi/domain/members/exception/ErrorMessage.java
  src/main/java/com/gachtaxi/domain/members/exception/InvalidNicknameLengthException.java
  src/main/java/com/gachtaxi/domain/members/service/MemberService.java
Labels: 🔨 Refactor, ✨ Feature

#140 Refactor #140 방장 혼자서 마감시 매칭 취소
  src/main/java/com/gachtaxi/domain/matching/common/controller/ManualMatchingController.java
  src/main/java/com/gachtaxi/domain/matching/common/controller/ResponseMessage.java
  src/main/java/com/gachtaxi/domain/matching/common/service/ManualMatchingService.java
Labels: 🔨 Refactor

#135 Fix #133 AT RT responsebody 반환
  src/main/java/com/gachtaxi/domain/members/controller/AuthController.java
  src/main/java/com/gachtaxi/domain/members/dto/response/MemberLoginResponseDto.java
  src/main/java/com/gachtaxi/global/auth/jwt/dto/JwtTokenDto.java
  src/main/java/com/gachtaxi/global/auth/jwt/dto/RefreshTokenDto.java
  src/main/java/com/gachtaxi/global/config/SecurityConfig.java
Labels: 💻 Fix

#143 Refactor #143 매칭 태그 enum 변경
  src/main/java/com/gachtaxi/domain/matching/common/dto/response/MatchingRoomResponse.java
  src/main/java/com/gachtaxi/domain/matching/common/entity/enums/Tags.java
  src/main/java/com/gachtaxi/domain/matching/common/exception/ErrorMessage.java
  src/main/java/com/gachtaxi/domain/matching/common/exception/NotMatchingGenderException.java
  src/main/java/com/gachtaxi/domain/matching/common/service/ManualMatchingService.java
Labels: 🔨 Refactor

#138 Feat #138 dm 기능 구현
  src/main/java/com/gachtaxi/domain/friend/dto/response/FriendsResponseDto.java
  src/main/java/com/gachtaxi/domain/friend/entity/Friends.java
  src/main/java/com/gachtaxi/domain/friend/mapper/FriendsMapper.java
  src/main/java/com/gachtaxi/domain/friend/service/FriendService.java
Labels: ✨ Feature
