Repository Leets-Official/GachTaxi-BE, pull requests merged in 2025-02, with the labels that each got.

#54 Feat #54 이미지 추가해서 반환
  src/main/java/com/gachtaxi/domain/chat/controller/ChattingController.java
  src/main/java/com/gachtaxi/domain/chat/controller/ResponseMessage.java
  src/main/java/com/gachtaxi/domain/chat/dto/request/ChatMessage.java
  src/main/java/com/gachtaxi/domain/chat/dto/response/ChatResponse.java
  src/main/java/com/gachtaxi/domain/chat/dto/response/ChattingMessageResponse.java
  src/main/java/com/gachtaxi/domain/chat/dto/response/ChattingRoomCountResponse.java
  src/main/java/com/gachtaxi/domain/chat/entity/ChattingMessage.java
  src/main/java/com/gachtaxi/domain/chat/entity/ChattingParticipant.java
  src/main/java/com/gachtaxi/domain/chat/service/ChattingRedisService.java
  src/main/java/com/gachtaxi/domain/chat/service/ChattingRoomService.java
  src/main/java/com/gachtaxi/domain/chat/service/ChattingService.java
Labels: 🔨 Refactor, ✨ Feature

#56 Feat #42 친구 관련 기능 구현
  src/main/java/com/gachtaxi/domain/friend/controller/FriendController.java
  src/main/java/com/gachtaxi/domain/friend/controller/ResponseMessage.java
  src/main/java/com/gachtaxi/domain/friend/dto/request/FriendRequestDto.java
  src/main/java/com/gachtaxi/domain/friend/dto/request/FriendStatusUpdateReqeustDto.java
  src/main/java/com/gachtaxi/domain/friend/dto/request/FriendUpdateDto.java
  src/main/java/com/gachtaxi/domain/friend/dto/response/FriendsPageableResponse.java
  src/main/java/com/gachtaxi/domain/friend/dto/response/FriendsResponseDto.java
  src/main/java/com/gachtaxi/domain/friend/dto/response/FriendsSliceResponse.java
  src/main/java/com/gachtaxi/domain/friend/entity/Friends.java
  src/main/java/com/gachtaxi/domain/friend/entity/enums/FriendStatus.java
  src/main/java/com/gachtaxi/domain/friend/exception/ErrorMessage.java
  src/main/java/com/gachtaxi/domain/friend/exception/FriendNotExistsException.java
  src/main/java/com/gachtaxi/domain/friend/exception/FriendShipDoesNotSendMySelfException.java
  src/main/java/com/gachtaxi/domain/friend/exception/FriendShipExistsException.java
  src/main/java/com/gachtaxi/domain/friend/exception/FriendShipPendingException.java
  src/main/java/com/gachtaxi/domain/friend/mapper/FriendsMapper.java
  src/main/java/com/gachtaxi/domain/friend/repository/FriendRepository.java
  src/main/java/com/gachtaxi/domain/friend/service/FriendService.java
  src/main/java/com/gachtaxi/domain/members/repository/MemberRepository.java
  src/main/java/com/gachtaxi/domain/members/service/MemberService.java
  src/main/java/com/gachtaxi/global/config/PermitUrlConfig.java
Labels: ✨ Feature

#63 Feat/#63/수동매칭 CRUD 구현
  src/main/java/com/gachtaxi/domain/matching/algorithm/service/MatchingAlgorithmService.java
  src/main/java/com/gachtaxi/domain/matching/algorithm/service/MatchingAlgorithmServiceImpl.java
  src/main/java/com/gachtaxi/domain/matching/common/controller/ManualMatchingController.java
  src/main/java/com/gachtaxi/domain/matching/common/controller/ResponseMessage.java
  src/main/java/com/gachtaxi/domain/matching/common/dto/request/ManualMatchingJoinRequest.java
  src/main/java/com/gachtaxi/domain/matching/common/dto/request/ManualMatchingRequest.java
  src/main/java/com/gachtaxi/domain/matching/common/dto/response/MatchingPageableResponse.java
  src/main/java/com/gachtaxi/domain/matching/common/dto/response/MatchingRoomListResponse.java
  src/main/java/com/gachtaxi/domain/matching/common/dto/response/MatchingRoomResponse.java
  src/main/java/com/gachtaxi/domain/matching/common/entity/MatchingRoom.java
  src/main/java/com/gachtaxi/domain/matching/common/entity/MatchingRoomTagInfo.java
  src/main/java/com/gachtaxi/domain/matching/common/entity/Route.java
  src/main/java/com/gachtaxi/domain/matching/common/entity/enums/MatchingRoomType.java
  src/main/java/com/gachtaxi/domain/matching/common/exception/ErrorMessage.java
  src/main/java/com/gachtaxi/domain/matching/common/exception/NotEqualStartAndDestinationException.java
  src/main/java/com/gachtaxi/domain/matching/common/exception/RoomMasterCantJoinException.java
  src/main/java/com/gachtaxi/domain/matching/common/repository/MatchingRoomRepository.java
  src/main/java/com/gachtaxi/domain/matching/common/repository/MemberMatchingRoomChargingInfoRepository.java
  src/main/java/com/gachtaxi/domain/matching/common/repository/RouteRepository.java
  src/main/java/com/gachtaxi/domain/matching/common/service/ManualMatchingService.java
  src/main/java/com/gachtaxi/domain/matching/common/service/MatchingRoomService.java
Labels: 🔨 Refactor, ✨ Feature

#71 Refactor #71 알림 삭제 수정 및 주석 해제
  src/main/java/com/gachtaxi/domain/notification/controller/NotificationController.java
  src/main/java/com/gachtaxi/domain/notification/entity/payload/FriendRequestPayload.java
  src/main/java/com/gachtaxi/domain/notification/repository/NotificationRepository.java
  src/main/java/com/gachtaxi/domain/notification/service/NotificationService.java
Labels: 🔨 Refactor

#67 Feat/#66/블랙리스트기능구현
  src/main/java/com/gachtaxi/domain/matching/algorithm/service/MatchingAlgorithmServiceImpl.java
  src/main/java/com/gachtaxi/domain/matching/common/entity/MatchingRoom.java
  src/main/java/com/gachtaxi/domain/members/controller/BlacklistController.java
  src/main/java/com/gachtaxi/domain/members/controller/ResponseMessage.java
  src/main/java/com/gachtaxi/domain/members/dto/response/BlacklistGetResponse.java
  src/main/java/com/gachtaxi/domain/members/dto/response/BlacklistPostResponse.java
  src/main/java/com/gachtaxi/domain/members/entity/Blacklists.java
  src/main/java/com/gachtaxi/domain/members/exception/BlacklistAlreadyExistsException.java
  src/main/java/com/gachtaxi/domain/members/exception/BlacklistNotFoundException.java
  src/main/java/com/gachtaxi/domain/members/exception/BlacklistRequesterEqualsReceiverException.java
  src/main/java/com/gachtaxi/domain/members/exception/ErrorMessage.java
  src/main/java/com/gachtaxi/domain/members/repository/BlacklistsRepository.java
  src/main/java/com/gachtaxi/domain/members/service/BlacklistService.java
Labels: ✨ Feature

#76 Feat/#75/매칭 친구오류수정
  src/main/java/com/gachtaxi/domain/friend/dto/response/FriendsPageableResponse.java
  src/main/java/com/gachtaxi/domain/matching/common/repository/MatchingRoomRepository.java
  src/main/java/com/gachtaxi/global/auth/jwt/filter/JwtAuthenticationFilter.java
Labels: 💻 Fix, 🐞 Bug

#51 Fix #51 유니크 추가 및 post send 구현
  src/main/java/com/gachtaxi/domain/chat/entity/ChattingParticipant.java
  src/main/java/com/gachtaxi/domain/chat/service/ChattingRoomService.java
  src/main/java/com/gachtaxi/domain/chat/stomp/CustomChannelInterceptor.java
  src/main/java/com/gachtaxi/domain/chat/stomp/strategy/ChatStrategyHandler.java
  src/main/java/com/gachtaxi/domain/chat/stomp/strategy/StompCommandStrategy.java
  src/main/java/com/gachtaxi/domain/chat/stomp/strategy/StompSubscribeStrategy.java
  src/main/java/com/gachtaxi/global/config/WebSocketConfig.java
Labels: 🔨 Refactor, 💻 Fix

#60 Feat #59 사용자 관련 api 구현
  src/main/java/com/gachtaxi/domain/members/controller/MemberController.java
  src/main/java/com/gachtaxi/domain/members/controller/ResponseMessage.java
  src/main/java/com/gachtaxi/domain/members/dto/request/MemberInfoRequestDto.java
  src/main/java/com/gachtaxi/domain/members/dto/request/MemberIntegrationRequestDto.java
  src/main/java/com/gachtaxi/domain/members/dto/response/MemberResponseDto.java
  src/main/java/com/gachtaxi/domain/members/entity/Members.java
  src/main/java/com/gachtaxi/domain/members/service/MemberService.java
Labels: ✨ Feature

#73 Feat #73 수동매칭 로직 고도화
  src/main/java/com/gachtaxi/domain/friend/service/FriendService.java
  src/main/java/com/gachtaxi/domain/matching/common/controller/ManualMatchingController.java
  src/main/java/com/gachtaxi/domain/matching/common/controller/ResponseMessage.java
  src/main/java/com/gachtaxi/domain/matching/common/dto/request/ManualMatchingRequest.java
  src/main/java/com/gachtaxi/domain/matching/common/dto/response/MatchingRoomResponse.java
  src/main/java/com/gachtaxi/domain/matching/common/entity/MatchingRoom.java
  src/main/java/com/gachtaxi/domain/matching/common/exception/ErrorMessage.java
  src/main/java/com/gachtaxi/domain/matching/common/exception/MatchingRoomAlreadyFullException.java
  src/main/java/com/gachtaxi/domain/matching/common/exception/NoSuchInvitationException.java
  src/main/java/com/gachtaxi/domain/matching/common/service/ManualMatchingService.java
  src/main/java/com/gachtaxi/domain/matching/common/service/MatchingInvitationService.java
  src/main/java/com/gachtaxi/domain/members/repository/MemberRepository.java
  src/main/java/com/gachtaxi/domain/notification/entity/enums/NotificationType.java
  src/main/java/com/gachtaxi/domain/notification/entity/payload/MatchingInvitePayload.java
  src/main/java/com/gachtaxi/domain/notification/repository/NotificationRepository.java
  src/main/java/com/gachtaxi/domain/notification/service/NotificationService.java
Labels: ✨ Feature

#79 Refactor #79 수동매칭 블랙리스트 및 채팅방 설정
  src/main/java/com/gachtaxi/domain/chat/service/ChattingRoomService.java
  src/main/java/com/gachtaxi/domain/matching/common/controller/ManualMatchingController.java
  src/main/java/com/gachtaxi/domain/matching/common/dto/response/MatchingPageableResponse.java
  src/main/java/com/gachtaxi/domain/matching/common/dto/response/MatchingRoomListResponse.java
  src/main/java/com/gachtaxi/domain/matching/common/dto/response/MatchingRoomResponse.java
  src/main/java/com/gachtaxi/domain/matching/common/entity/MatchingRoom.java
  src/main/java/com/gachtaxi/domain/matching/common/service/ManualMatchingService.java
  src/main/java/com/gachtaxi/domain/members/exception/BlacklistedUserCannotJoinException.java
  src/main/java/com/gachtaxi/domain/members/exception/ErrorMessage.java
  src/main/java/com/gachtaxi/domain/members/service/BlacklistService.java
Labels: 🔨 Refactor, ✨ Feature

#80 Feat #80 채팅 프로필 수정
  src/main/java/com/gachtaxi/domain/chat/repository/ChattingMessageMongoRepository.java
  src/main/java/com/gachtaxi/domain/members/service/MemberService.java
  src/main/java/com/gachtaxi/global/config/SesClientConfig.java
Labels: ✨ Feature

#69 Feat/#68/매칭방 채팅방연결로직구현
  src/main/java/com/gachtaxi/domain/chat/controller/ChattingController.java
  src/main/java/com/gachtaxi/domain/chat/service/ChattingRoomService.java
  src/main/java/com/gachtaxi/domain/matching/algorithm/dto/FindRoomResult.java
  src/main/java/com/gachtaxi/domain/matching/common/entity/MatchingRoom.java
  src/main/java/com/gachtaxi/domain/matching/common/service/AutoMatchingService.java
  src/main/java/com/gachtaxi/domain/matching/common/service/MatchingRoomService.java
  src/main/java/com/gachtaxi/domain/matching/event/MatchingEventFactory.java
  src/main/java/com/gachtaxi/domain/matching/event/dto/kafka_topic/MatchMemberJoinedEvent.java
  src/main/java/com/gachtaxi/domain/matching/event/dto/kafka_topic/MatchRoomCreatedEvent.java
  src/main/java/com/gachtaxi/domain/matching/event/service/kafka/AutoMatchingConsumer.java
Labels: ✨ Feature

#91 Feat/#89/계좌번호 수정 api 구현
  src/main/java/com/gachtaxi/domain/matching/common/entity/MatchingRoom.java
  src/main/java/com/gachtaxi/domain/members/controller/AccountController.java
  src/main/java/com/gachtaxi/domain/members/controller/ResponseMessage.java
  src/main/java/com/gachtaxi/domain/members/dto/request/AccountPostRequest.java
  src/main/java/com/gachtaxi/domain/members/dto/response/AccountGetResponse.java
  src/main/java/com/gachtaxi/domain/members/entity/Members.java
  src/main/java/com/gachtaxi/domain/members/service/AccountService.java
Labels: ✨ Feature

#85 Refactor/#84프론트엔드 요구사항반영
  src/main/java/com/gachtaxi/domain/matching/algorithm/service/MatchingAlgorithmServiceImpl.java
  src/main/java/com/gachtaxi/domain/matching/common/exception/AlreadyInMatchingRoomException.java
  src/main/java/com/gachtaxi/domain/matching/common/repository/MatchingRoomRepository.java
  src/main/java/com/gachtaxi/domain/members/dto/response/BlacklistGetResponse.java
  src/main/java/com/gachtaxi/domain/members/entity/Blacklists.java
Labels: 🔨 Refactor

#83 Feat #83 웹소켓 CORS 해제
  src/main/java/com/gachtaxi/global/config/WebSocketConfig.java
Labels: ✨ Feature

#97 Refactor #97 수동매칭 수락 거절 구현
  src/main/java/com/gachtaxi/domain/matching/common/controller/ManualMatchingController.java
  src/main/java/com/gachtaxi/domain/matching/common/controller/ResponseMessage.java
  src/main/java/com/gachtaxi/domain/matching/common/dto/request/ManualMatchingInviteReplyRequest.java
  src/main/java/com/gachtaxi/domain/matching/common/dto/response/MatchingPageableResponse.java
  src/main/java/com/gachtaxi/domain/matching/common/dto/response/MatchingRoomListResponse.java
  src/main/java/com/gachtaxi/domain/matching/common/entity/enums/MatchingInviteStatus.java
  src/main/java/com/gachtaxi/domain/matching/common/service/MatchingInvitationService.java
Labels: 🔨 Refactor

#99 Refactor #99 회원정보 수정 API 수정
  src/main/java/com/gachtaxi/domain/members/dto/request/MemberInfoRequestDto.java
  src/main/java/com/gachtaxi/domain/members/entity/Members.java
Labels: 🔨 Refactor

#100 Fix #100 친구 API 수정
  src/main/java/com/gachtaxi/domain/friend/controller/FriendController.java
  src/main/java/com/gachtaxi/domain/friend/dto/request/FriendUpdateDto.java
  src/main/java/com/gachtaxi/domain/friend/entity/enums/FriendStatus.java
  src/main/java/com/gachtaxi/domain/friend/service/FriendService.java
Labels: 💻 Fix

#95 Feat #95 회원탈퇴 API 구현
  src/main/java/com/gachtaxi/domain/members/controller/MemberController.java
  src/main/java/com/gachtaxi/domain/members/controller/ResponseMessage.java
  src/main/java/com/gachtaxi/domain/members/entity/Members.java
  src/main/java/com/gachtaxi/domain/members/entity/enums/UserStatus.java
  src/main/java/com/gachtaxi/domain/members/repository/MemberRepository.java
  src/main/java/com/gachtaxi/domain/members/service/MemberDeleteService.java
  src/main/java/com/gachtaxi/domain/members/service/MemberService.java
Labels: ✨ Feature

#104 fix: blacklist 조회 응답에 profilePicture 필드에 gender가 들어가는 오류 수정
  src/main/java/com/gachtaxi/domain/members/dto/response/BlacklistGetResponse.java
Labels: 💻 Fix, 🐞 Bug

#106 Refactor #106 쿠키 도메인 설정하도록 수정
  src/main/java/com/gachtaxi/global/auth/jwt/util/CookieUtil.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: 💻 Fix

#107 Refactor #107 departuretime 변수형 및 자동매칭 수정
  src/main/java/com/gachtaxi/domain/matching/algorithm/service/MatchingAlgorithmService.java
  src/main/java/com/gachtaxi/domain/matching/algorithm/service/MatchingAlgorithmServiceImpl.java
  src/main/java/com/gachtaxi/domain/matching/common/dto/request/AutoMatchingPostRequest.java
  src/main/java/com/gachtaxi/domain/matching/common/dto/response/MatchingRoomResponse.java
  src/main/java/com/gachtaxi/domain/matching/common/entity/MatchingRoom.java
  src/main/java/com/gachtaxi/domain/matching/common/repository/MatchingRoomRepository.java
  src/main/java/com/gachtaxi/domain/matching/common/service/AutoMatchingService.java
  src/main/java/com/gachtaxi/domain/matching/common/service/ManualMatchingService.java
  src/main/java/com/gachtaxi/domain/matching/common/service/MatchingRoomService.java
  src/main/java/com/gachtaxi/domain/matching/event/dto/kafka_topic/MatchRoomCreatedEvent.java
Labels: 🔨 Refactor

#115 Fix #115 나의 매칭 리스트 쿼리 조건 수정
  src/main/java/com/gachtaxi/domain/matching/common/repository/MatchingRoomRepository.java
Labels: 💻 Fix, ✅ Test

#117 Fix #117 자동 매칭방 탐색시 타입이 수동인 매칭방을 제외하고 탐색
  src/main/java/com/gachtaxi/domain/matching/common/entity/MatchingRoom.java
  src/main/java/com/gachtaxi/domain/matching/common/repository/MatchingRoomRepository.java
Labels: 💻 Fix

#126 Refactor #126 수동매칭 요청반환 데이터 변경
  src/main/java/com/gachtaxi/domain/matching/common/dto/request/ManualMatchingRequest.java
  src/main/java/com/gachtaxi/domain/matching/common/dto/response/MatchingRoomResponse.java
  src/main/java/com/gachtaxi/domain/matching/common/entity/MatchingRoom.java
  src/main/java/com/gachtaxi/domain/matching/common/service/ManualMatchingService.java
  src/main/java/com/gachtaxi/domain/matching/common/service/MatchingInvitationService.java
  src/main/java/com/gachtaxi/domain/notification/entity/payload/MatchingInvitePayload.java
Labels: 🔨 Refactor

#119 Fix #119 프로필 수정 시 닉네임 중복 체크 추가
  src/main/java/com/gachtaxi/domain/members/service/MemberService.java
Labels: 💻 Fix
