Repository Leets-Official/GachTaxi-BE, pull requests merged in 2025-04, with the labels that each got.

#146 Refactor #146 isLast로 페이저블 dto 통일
  src/main/java/com/gachtaxi/domain/chat/dto/response/ChatPageableResponse.java
  src/main/java/com/gachtaxi/domain/friend/dto/response/FriendsPageableResponse.java
  src/main/java/com/gachtaxi/domain/matching/common/dto/response/MatchingPageableResponse.java
  src/main/java/com/gachtaxi/domain/members/dto/response/BlacklistGetResponse.java
  src/main/java/com/gachtaxi/domain/notification/dto/response/NotificationPageableResponse.java
Labels: 🔨 Refactor

#151 Feat #151 공지사항 조회 기능 구현
  src/main/java/com/gachtaxi/domain/notice/controller/NoticeController.java
  src/main/java/com/gachtaxi/domain/notice/controller/ResponseMessage.java
  src/main/java/com/gachtaxi/domain/notice/dto/response/NoticeDTO.java
  src/main/java/com/gachtaxi/domain/notice/dto/response/NoticeListResponse.java
  src/main/java/com/gachtaxi/domain/notice/dto/response/NoticePageableResponse.java
  src/main/java/com/gachtaxi/domain/notice/entity/Notice.java
  src/main/java/com/gachtaxi/domain/notice/exception/ErrorMessage.java
  src/main/java/com/gachtaxi/domain/notice/exception/NoticeNotFoundException.java
  src/main/java/com/gachtaxi/domain/notice/repository/NoticeRepository.java
  src/main/java/com/gachtaxi/domain/notice/service/NoticeFindService.java
  src/main/java/com/gachtaxi/domain/notice/service/NoticeService.java
Labels: ✨ Feature

#144 Feat #144 친구 리스트 검색 기능
  src/main/java/com/gachtaxi/domain/members/controller/MemberController.java
  src/main/java/com/gachtaxi/domain/members/controller/ResponseMessage.java
  src/main/java/com/gachtaxi/domain/members/dto/response/MemberPageableResponse.java
  src/main/java/com/gachtaxi/domain/members/dto/response/MemberSliceResponse.java
  src/main/java/com/gachtaxi/domain/members/dto/response/MemberSummaryResponse.java
  src/main/java/com/gachtaxi/domain/members/repository/MemberRepository.java
  src/main/java/com/gachtaxi/domain/members/service/MemberService.java
Labels: ✨ Feature

#153 Feat #153 어드민 공지사항 작성, 수정, 삭제 구현
  src/main/java/com/gachtaxi/domain/notice/controller/AdminNoticeController.java
  src/main/java/com/gachtaxi/domain/notice/controller/NoticeController.java
  src/main/java/com/gachtaxi/domain/notice/controller/ResponseMessage.java
  src/main/java/com/gachtaxi/domain/notice/dto/request/NoticeCreateRequest.java
  src/main/java/com/gachtaxi/domain/notice/dto/request/NoticeUpdateRequest.java
  src/main/java/com/gachtaxi/domain/notice/entity/Notice.java
  src/main/java/com/gachtaxi/domain/notice/service/NoticeAdminService.java
  src/main/java/com/gachtaxi/global/config/PermitUrlConfig.java
Labels: 🔨 Refactor, ✨ Feature
